#pragma once

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace PalServer::Params
{

// Function BP_SkillEffect_SeedMine_Seed.BP_SkillEffect_SeedMine_Seed_C.BndEvt__BP_SkillEffect_SeedMine_Seed_collision_0_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature
// 0x0108 (0x0108 - 0x0000)
struct BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_collision_0_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFromSweep;                                        // 0x001C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             SweepResult;                                       // 0x0020(0x00E8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_collision_0_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_collision_0_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(sizeof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_collision_0_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature) == 0x000108, "Wrong size on BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_collision_0_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_collision_0_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_collision_0_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_collision_0_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_collision_0_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_collision_0_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_collision_0_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_collision_0_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_collision_0_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_collision_0_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, bFromSweep) == 0x00001C, "Member 'BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_collision_0_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::bFromSweep' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_collision_0_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, SweepResult) == 0x000020, "Member 'BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_collision_0_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::SweepResult' has a wrong offset!");

// Function BP_SkillEffect_SeedMine_Seed.BP_SkillEffect_SeedMine_Seed_C.BndEvt__BP_SkillEffect_SeedMine_Seed_GetLengBullet_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature
// 0x0108 (0x0108 - 0x0000)
struct BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_GetLengBullet_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFromSweep;                                        // 0x001C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             SweepResult;                                       // 0x0020(0x00E8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_GetLengBullet_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_GetLengBullet_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(sizeof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_GetLengBullet_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature) == 0x000108, "Wrong size on BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_GetLengBullet_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_GetLengBullet_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_GetLengBullet_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_GetLengBullet_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_GetLengBullet_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_GetLengBullet_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_GetLengBullet_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_GetLengBullet_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_GetLengBullet_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_GetLengBullet_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature, bFromSweep) == 0x00001C, "Member 'BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_GetLengBullet_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature::bFromSweep' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_GetLengBullet_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature, SweepResult) == 0x000020, "Member 'BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_GetLengBullet_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature::SweepResult' has a wrong offset!");

// Function BP_SkillEffect_SeedMine_Seed.BP_SkillEffect_SeedMine_Seed_C.BndEvt__BP_SkillEffect_SeedMine_Seed_HitLeng_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature
// 0x0108 (0x0108 - 0x0000)
struct BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_HitLeng_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFromSweep;                                        // 0x001C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             SweepResult;                                       // 0x0020(0x00E8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_HitLeng_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_HitLeng_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(sizeof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_HitLeng_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature) == 0x000108, "Wrong size on BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_HitLeng_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_HitLeng_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_HitLeng_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_HitLeng_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_HitLeng_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_HitLeng_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_HitLeng_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_HitLeng_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_HitLeng_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_HitLeng_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature, bFromSweep) == 0x00001C, "Member 'BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_HitLeng_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature::bFromSweep' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_HitLeng_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature, SweepResult) == 0x000020, "Member 'BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_HitLeng_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature::SweepResult' has a wrong offset!");

// Function BP_SkillEffect_SeedMine_Seed.BP_SkillEffect_SeedMine_Seed_C.BndEvt__BP_SkillEffect_SeedMine_Seed_MovementSphereRoot_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature
// 0x0118 (0x0118 - 0x0000)
struct BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_MovementSphereRoot_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    HitComponent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector                                NormalImpulse;                                     // 0x0018(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             Hit;                                               // 0x0030(0x00E8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_MovementSphereRoot_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature) == 0x000008, "Wrong alignment on BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_MovementSphereRoot_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature");
static_assert(sizeof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_MovementSphereRoot_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature) == 0x000118, "Wrong size on BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_MovementSphereRoot_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_MovementSphereRoot_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature, HitComponent) == 0x000000, "Member 'BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_MovementSphereRoot_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature::HitComponent' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_MovementSphereRoot_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_MovementSphereRoot_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_MovementSphereRoot_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_MovementSphereRoot_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_MovementSphereRoot_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature, NormalImpulse) == 0x000018, "Member 'BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_MovementSphereRoot_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature::NormalImpulse' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_MovementSphereRoot_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature, Hit) == 0x000030, "Member 'BP_SkillEffect_SeedMine_Seed_C_BndEvt__BP_SkillEffect_SeedMine_Seed_MovementSphereRoot_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature::Hit' has a wrong offset!");

// Function BP_SkillEffect_SeedMine_Seed.BP_SkillEffect_SeedMine_Seed_C.ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed
// 0x0610 (0x0610 - 0x0000)
struct BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_RandomFloat_ReturnValue;                  // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent_2;  // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor_3;           // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp_3;            // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex_2;       // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bFromSweep_2;           // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35[0x3];                                       // 0x0035(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_ComponentBoundEvent_SweepResult_2;          // 0x0038(0x00E8)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_121[0x7];                                      // 0x0121(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_SkillEffect_SeedMine_Seed_C*        K2Node_DynamicCast_AsBP_Skill_Effect_Seed_Mine_Seed; // 0x0128(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0131(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_132[0x6];                                      // 0x0132(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent_1;  // 0x0138(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor_2;           // 0x0140(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp_2;            // 0x0148(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex_1;       // 0x0150(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bFromSweep_1;           // 0x0154(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_155[0x3];                                      // 0x0155(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_ComponentBoundEvent_SweepResult_1;          // 0x0158(0x00E8)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent;    // 0x0240(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor_1;           // 0x0248(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp_1;            // 0x0250(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex;         // 0x0258(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bFromSweep;             // 0x025C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_25D[0x3];                                      // 0x025D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_ComponentBoundEvent_SweepResult;            // 0x0260(0x00E8)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue;               // 0x0348(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_SkillEffect_SeedMine_Seed_C*        K2Node_DynamicCast_AsBP_Skill_Effect_Seed_Mine_Seed_1; // 0x0350(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0358(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_359[0x7];                                      // 0x0359(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_SkillEffect_SeedMine_C*             K2Node_DynamicCast_AsBP_Skill_Effect_Seed_Mine;    // 0x0360(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0368(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_369[0x3];                                      // 0x0369(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Event_DeltaSeconds;                         // 0x036C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0370(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue_1;           // 0x0378(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x0380(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0398(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x03B0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetWorldLocation_SweepHitResult;       // 0x03C8(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue_1;             // 0x04B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x04B8(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ClassClass_ReturnValue;          // 0x04C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4C9[0x7];                                      // 0x04C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_HitComponent;           // 0x04D0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor;             // 0x04D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp;              // 0x04E0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_ComponentBoundEvent_NormalImpulse;          // 0x04E8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_ComponentBoundEvent_Hit;                    // 0x0500(0x00E8)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x05E8(0x0008)(NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x05F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x05F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsApplicableDamage_ReturnValue;           // 0x05FC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x05FD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x05FE(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5FF[0x1];                                      // 0x05FF(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast;     // 0x0600(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_VariableSet_ProjectileGravityScale_ImplicitCast; // 0x0608(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Delay_Duration_ImplicitCast;              // 0x060C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed) == 0x000008, "Wrong alignment on BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed");
static_assert(sizeof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed) == 0x000610, "Wrong size on BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, EntryPoint) == 0x000000, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, CallFunc_RandomFloat_ReturnValue) == 0x000008, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::CallFunc_RandomFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000010, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_ComponentBoundEvent_OverlappedComponent_2) == 0x000018, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_ComponentBoundEvent_OverlappedComponent_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_ComponentBoundEvent_OtherActor_3) == 0x000020, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_ComponentBoundEvent_OtherActor_3' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_ComponentBoundEvent_OtherComp_3) == 0x000028, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_ComponentBoundEvent_OtherComp_3' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_ComponentBoundEvent_OtherBodyIndex_2) == 0x000030, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_ComponentBoundEvent_OtherBodyIndex_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_ComponentBoundEvent_bFromSweep_2) == 0x000034, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_ComponentBoundEvent_bFromSweep_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_ComponentBoundEvent_SweepResult_2) == 0x000038, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_ComponentBoundEvent_SweepResult_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, CallFunc_NotEqual_ObjectObject_ReturnValue) == 0x000120, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::CallFunc_NotEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_DynamicCast_AsBP_Skill_Effect_Seed_Mine_Seed) == 0x000128, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_DynamicCast_AsBP_Skill_Effect_Seed_Mine_Seed' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_DynamicCast_bSuccess) == 0x000130, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, Temp_bool_IsClosed_Variable) == 0x000131, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_ComponentBoundEvent_OverlappedComponent_1) == 0x000138, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_ComponentBoundEvent_OverlappedComponent_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_ComponentBoundEvent_OtherActor_2) == 0x000140, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_ComponentBoundEvent_OtherActor_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_ComponentBoundEvent_OtherComp_2) == 0x000148, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_ComponentBoundEvent_OtherComp_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_ComponentBoundEvent_OtherBodyIndex_1) == 0x000150, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_ComponentBoundEvent_OtherBodyIndex_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_ComponentBoundEvent_bFromSweep_1) == 0x000154, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_ComponentBoundEvent_bFromSweep_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_ComponentBoundEvent_SweepResult_1) == 0x000158, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_ComponentBoundEvent_SweepResult_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_ComponentBoundEvent_OverlappedComponent) == 0x000240, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_ComponentBoundEvent_OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_ComponentBoundEvent_OtherActor_1) == 0x000248, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_ComponentBoundEvent_OtherActor_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_ComponentBoundEvent_OtherComp_1) == 0x000250, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_ComponentBoundEvent_OtherComp_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_ComponentBoundEvent_OtherBodyIndex) == 0x000258, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_ComponentBoundEvent_OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_ComponentBoundEvent_bFromSweep) == 0x00025C, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_ComponentBoundEvent_bFromSweep' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_ComponentBoundEvent_SweepResult) == 0x000260, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_ComponentBoundEvent_SweepResult' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, CallFunc_GetObjectClass_ReturnValue) == 0x000348, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::CallFunc_GetObjectClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_DynamicCast_AsBP_Skill_Effect_Seed_Mine_Seed_1) == 0x000350, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_DynamicCast_AsBP_Skill_Effect_Seed_Mine_Seed_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_DynamicCast_bSuccess_1) == 0x000358, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_DynamicCast_AsBP_Skill_Effect_Seed_Mine) == 0x000360, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_DynamicCast_AsBP_Skill_Effect_Seed_Mine' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_DynamicCast_bSuccess_2) == 0x000368, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_Event_DeltaSeconds) == 0x00036C, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, CallFunc_Add_DoubleDouble_ReturnValue) == 0x000370, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, CallFunc_Add_DoubleDouble_ReturnValue_1) == 0x000378, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::CallFunc_Add_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, CallFunc_MakeVector_ReturnValue) == 0x000380, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000398, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, CallFunc_Add_VectorVector_ReturnValue) == 0x0003B0, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, CallFunc_K2_SetWorldLocation_SweepHitResult) == 0x0003C8, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::CallFunc_K2_SetWorldLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, CallFunc_GetObjectClass_ReturnValue_1) == 0x0004B0, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::CallFunc_GetObjectClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_CreateDelegate_OutputDelegate) == 0x0004B8, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, CallFunc_NotEqual_ClassClass_ReturnValue) == 0x0004C8, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::CallFunc_NotEqual_ClassClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_ComponentBoundEvent_HitComponent) == 0x0004D0, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_ComponentBoundEvent_HitComponent' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_ComponentBoundEvent_OtherActor) == 0x0004D8, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_ComponentBoundEvent_OtherActor' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_ComponentBoundEvent_OtherComp) == 0x0004E0, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_ComponentBoundEvent_OtherComp' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_ComponentBoundEvent_NormalImpulse) == 0x0004E8, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_ComponentBoundEvent_NormalImpulse' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_ComponentBoundEvent_Hit) == 0x000500, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_ComponentBoundEvent_Hit' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x0005E8, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, CallFunc_GetOwner_ReturnValue) == 0x0005F0, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::CallFunc_GetOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, CallFunc_Array_Add_ReturnValue) == 0x0005F8, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, CallFunc_IsApplicableDamage_ReturnValue) == 0x0005FC, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::CallFunc_IsApplicableDamage_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, Temp_bool_Has_Been_Initd_Variable) == 0x0005FD, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, CallFunc_BooleanAND_ReturnValue) == 0x0005FE, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, CallFunc_Multiply_DoubleDouble_A_ImplicitCast) == 0x000600, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::CallFunc_Multiply_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, K2Node_VariableSet_ProjectileGravityScale_ImplicitCast) == 0x000608, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::K2Node_VariableSet_ProjectileGravityScale_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed, CallFunc_Delay_Duration_ImplicitCast) == 0x00060C, "Member 'BP_SkillEffect_SeedMine_Seed_C_ExecuteUbergraph_BP_SkillEffect_SeedMine_Seed::CallFunc_Delay_Duration_ImplicitCast' has a wrong offset!");

// Function BP_SkillEffect_SeedMine_Seed.BP_SkillEffect_SeedMine_Seed_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_SkillEffect_SeedMine_Seed_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SkillEffect_SeedMine_Seed_C_ReceiveTick) == 0x000004, "Wrong alignment on BP_SkillEffect_SeedMine_Seed_C_ReceiveTick");
static_assert(sizeof(BP_SkillEffect_SeedMine_Seed_C_ReceiveTick) == 0x000004, "Wrong size on BP_SkillEffect_SeedMine_Seed_C_ReceiveTick");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'BP_SkillEffect_SeedMine_Seed_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function BP_SkillEffect_SeedMine_Seed.BP_SkillEffect_SeedMine_Seed_C.SetRandomValueIntoNiagaraVariable
// 0x0018 (0x0018 - 0x0000)
struct BP_SkillEffect_SeedMine_Seed_C_SetRandomValueIntoNiagaraVariable final
{
public:
	class UNiagaraComponent*                      NiagaraComp;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_RandomFloatInRange_ReturnValue;           // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetVariableFloat_InValue_ImplicitCast;    // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SkillEffect_SeedMine_Seed_C_SetRandomValueIntoNiagaraVariable) == 0x000008, "Wrong alignment on BP_SkillEffect_SeedMine_Seed_C_SetRandomValueIntoNiagaraVariable");
static_assert(sizeof(BP_SkillEffect_SeedMine_Seed_C_SetRandomValueIntoNiagaraVariable) == 0x000018, "Wrong size on BP_SkillEffect_SeedMine_Seed_C_SetRandomValueIntoNiagaraVariable");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_SetRandomValueIntoNiagaraVariable, NiagaraComp) == 0x000000, "Member 'BP_SkillEffect_SeedMine_Seed_C_SetRandomValueIntoNiagaraVariable::NiagaraComp' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_SetRandomValueIntoNiagaraVariable, CallFunc_RandomFloatInRange_ReturnValue) == 0x000008, "Member 'BP_SkillEffect_SeedMine_Seed_C_SetRandomValueIntoNiagaraVariable::CallFunc_RandomFloatInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SeedMine_Seed_C_SetRandomValueIntoNiagaraVariable, CallFunc_SetVariableFloat_InValue_ImplicitCast) == 0x000010, "Member 'BP_SkillEffect_SeedMine_Seed_C_SetRandomValueIntoNiagaraVariable::CallFunc_SetVariableFloat_InValue_ImplicitCast' has a wrong offset!");

}

