#pragma once

#include "Basic.hpp"

#include "Pal_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace PalServer::Params
{

// Function BP_SkillEffect_SandTornadoBullet.BP_SkillEffect_SandTornadoBullet_C.BndEvt__BP_SkillEffect_SandTornadoBullet_AttackFilter_K2Node_ComponentBoundEvent_0_OnAttackDelegate__DelegateSignature
// 0x00E8 (0x00E8 - 0x0000)
struct BP_SkillEffect_SandTornadoBullet_C_BndEvt__BP_SkillEffect_SandTornadoBullet_AttackFilter_K2Node_ComponentBoundEvent_0_OnAttackDelegate__DelegateSignature final
{
public:
	class AActor*                                 Defencer;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FPalDamageInfo                         DamageInfo;                                        // 0x0008(0x00D0)(BlueprintVisible, BlueprintReadOnly, Parm)
	int32                                         HitCount;                                          // 0x00D8(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DC[0x4];                                       // 0x00DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    AttackerComponent;                                 // 0x00E0(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SkillEffect_SandTornadoBullet_C_BndEvt__BP_SkillEffect_SandTornadoBullet_AttackFilter_K2Node_ComponentBoundEvent_0_OnAttackDelegate__DelegateSignature) == 0x000008, "Wrong alignment on BP_SkillEffect_SandTornadoBullet_C_BndEvt__BP_SkillEffect_SandTornadoBullet_AttackFilter_K2Node_ComponentBoundEvent_0_OnAttackDelegate__DelegateSignature");
static_assert(sizeof(BP_SkillEffect_SandTornadoBullet_C_BndEvt__BP_SkillEffect_SandTornadoBullet_AttackFilter_K2Node_ComponentBoundEvent_0_OnAttackDelegate__DelegateSignature) == 0x0000E8, "Wrong size on BP_SkillEffect_SandTornadoBullet_C_BndEvt__BP_SkillEffect_SandTornadoBullet_AttackFilter_K2Node_ComponentBoundEvent_0_OnAttackDelegate__DelegateSignature");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_BndEvt__BP_SkillEffect_SandTornadoBullet_AttackFilter_K2Node_ComponentBoundEvent_0_OnAttackDelegate__DelegateSignature, Defencer) == 0x000000, "Member 'BP_SkillEffect_SandTornadoBullet_C_BndEvt__BP_SkillEffect_SandTornadoBullet_AttackFilter_K2Node_ComponentBoundEvent_0_OnAttackDelegate__DelegateSignature::Defencer' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_BndEvt__BP_SkillEffect_SandTornadoBullet_AttackFilter_K2Node_ComponentBoundEvent_0_OnAttackDelegate__DelegateSignature, DamageInfo) == 0x000008, "Member 'BP_SkillEffect_SandTornadoBullet_C_BndEvt__BP_SkillEffect_SandTornadoBullet_AttackFilter_K2Node_ComponentBoundEvent_0_OnAttackDelegate__DelegateSignature::DamageInfo' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_BndEvt__BP_SkillEffect_SandTornadoBullet_AttackFilter_K2Node_ComponentBoundEvent_0_OnAttackDelegate__DelegateSignature, HitCount) == 0x0000D8, "Member 'BP_SkillEffect_SandTornadoBullet_C_BndEvt__BP_SkillEffect_SandTornadoBullet_AttackFilter_K2Node_ComponentBoundEvent_0_OnAttackDelegate__DelegateSignature::HitCount' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_BndEvt__BP_SkillEffect_SandTornadoBullet_AttackFilter_K2Node_ComponentBoundEvent_0_OnAttackDelegate__DelegateSignature, AttackerComponent) == 0x0000E0, "Member 'BP_SkillEffect_SandTornadoBullet_C_BndEvt__BP_SkillEffect_SandTornadoBullet_AttackFilter_K2Node_ComponentBoundEvent_0_OnAttackDelegate__DelegateSignature::AttackerComponent' has a wrong offset!");

// Function BP_SkillEffect_SandTornadoBullet.BP_SkillEffect_SandTornadoBullet_C.ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet
// 0x0268 (0x0268 - 0x0000)
struct BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable; // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable_1;                     // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable_1;               // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable_2;                     // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable_1; // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable_2;               // 0x000B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue;        // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue;          // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SelectFloat_ReturnValue;                  // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FClamp_ReturnValue;                       // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetFloatValue_ReturnValue;                // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable_2; // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue_1;      // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SelectFloat_ReturnValue_1;                // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue_1;        // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FClamp_ReturnValue_1;                     // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetFloatValue_ReturnValue_1;              // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6C[0x4];                                       // 0x006C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_1;      // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable_3;                     // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable_3;               // 0x0079(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7A[0x6];                                       // 0x007A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue_2;      // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SelectFloat_ReturnValue_2;                // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue_2;        // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FClamp_ReturnValue_2;                     // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetFloatValue_ReturnValue_2;              // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A4[0x4];                                       // 0x00A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_2;      // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable_3; // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B1[0x7];                                       // 0x00B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue_3;      // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue_3;        // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SelectFloat_ReturnValue_3;                // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FClamp_ReturnValue_3;                     // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetFloatValue_ReturnValue_3;              // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DC[0x4];                                       // 0x00DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_3;      // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x00E8(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_Event_DeltaSecond;                          // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0100(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable_4;               // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_119[0x7];                                      // 0x0119(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraComponent*                      CallFunc_SpawnSystemAtLocation_ReturnValue;        // 0x0120(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0128(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable_4;                     // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_131[0x7];                                      // 0x0131(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_ComponentBoundEvent_Defencer;               // 0x0138(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FPalDamageInfo                         K2Node_ComponentBoundEvent_damageInfo;             // 0x0140(0x00D0)()
	int32                                         K2Node_ComponentBoundEvent_hitCount;               // 0x0210(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_214[0x4];                                      // 0x0214(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_AttackerComponent;      // 0x0218(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetFloatValue_InTime_ImplicitCast;        // 0x0220(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_224[0x4];                                      // 0x0224(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast;     // 0x0228(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetVariableFloat_InValue_ImplicitCast;    // 0x0230(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetFloatValue_InTime_ImplicitCast_1;      // 0x0234(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast_1;   // 0x0238(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetVariableFloat_InValue_ImplicitCast_1;  // 0x0240(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetFloatValue_InTime_ImplicitCast_2;      // 0x0244(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast_2;   // 0x0248(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetVariableFloat_InValue_ImplicitCast_2;  // 0x0250(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetFloatValue_InTime_ImplicitCast_3;      // 0x0254(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast_3;   // 0x0258(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetVariableFloat_InValue_ImplicitCast_3;  // 0x0260(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet) == 0x000008, "Wrong alignment on BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet");
static_assert(sizeof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet) == 0x000268, "Wrong size on BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, EntryPoint) == 0x000000, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, Temp_bool_IsClosed_Variable) == 0x000004, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable) == 0x000005, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, Temp_bool_Has_Been_Initd_Variable) == 0x000006, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, Temp_bool_IsClosed_Variable_1) == 0x000007, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::Temp_bool_IsClosed_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, Temp_bool_Has_Been_Initd_Variable_1) == 0x000008, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::Temp_bool_Has_Been_Initd_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, Temp_bool_IsClosed_Variable_2) == 0x000009, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::Temp_bool_IsClosed_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable_1) == 0x00000A, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, Temp_bool_Has_Been_Initd_Variable_2) == 0x00000B, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::Temp_bool_Has_Been_Initd_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_Subtract_DoubleDouble_ReturnValue) == 0x000010, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_Subtract_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_Divide_DoubleDouble_ReturnValue) == 0x000018, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_Divide_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_SelectFloat_ReturnValue) == 0x000020, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_SelectFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_FClamp_ReturnValue) == 0x000028, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_FClamp_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_GetFloatValue_ReturnValue) == 0x000030, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_GetFloatValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000038, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable_2) == 0x000040, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_Subtract_DoubleDouble_ReturnValue_1) == 0x000048, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_Subtract_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_SelectFloat_ReturnValue_1) == 0x000050, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_SelectFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_Divide_DoubleDouble_ReturnValue_1) == 0x000058, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_Divide_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_FClamp_ReturnValue_1) == 0x000060, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_FClamp_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_GetFloatValue_ReturnValue_1) == 0x000068, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_GetFloatValue_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_Multiply_DoubleDouble_ReturnValue_1) == 0x000070, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_Multiply_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, Temp_bool_IsClosed_Variable_3) == 0x000078, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::Temp_bool_IsClosed_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, Temp_bool_Has_Been_Initd_Variable_3) == 0x000079, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::Temp_bool_Has_Been_Initd_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_Subtract_DoubleDouble_ReturnValue_2) == 0x000080, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_Subtract_DoubleDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_SelectFloat_ReturnValue_2) == 0x000088, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_SelectFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_Divide_DoubleDouble_ReturnValue_2) == 0x000090, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_Divide_DoubleDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_FClamp_ReturnValue_2) == 0x000098, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_FClamp_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_GetFloatValue_ReturnValue_2) == 0x0000A0, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_GetFloatValue_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_Multiply_DoubleDouble_ReturnValue_2) == 0x0000A8, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_Multiply_DoubleDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable_3) == 0x0000B0, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_Subtract_DoubleDouble_ReturnValue_3) == 0x0000B8, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_Subtract_DoubleDouble_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_Divide_DoubleDouble_ReturnValue_3) == 0x0000C0, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_Divide_DoubleDouble_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_SelectFloat_ReturnValue_3) == 0x0000C8, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_SelectFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_FClamp_ReturnValue_3) == 0x0000D0, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_FClamp_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_GetFloatValue_ReturnValue_3) == 0x0000D8, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_GetFloatValue_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_Multiply_DoubleDouble_ReturnValue_3) == 0x0000E0, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_Multiply_DoubleDouble_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, K2Node_CreateDelegate_OutputDelegate) == 0x0000E8, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, K2Node_Event_DeltaSecond) == 0x0000F8, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::K2Node_Event_DeltaSecond' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000100, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, Temp_bool_Has_Been_Initd_Variable_4) == 0x000118, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::Temp_bool_Has_Been_Initd_Variable_4' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_SpawnSystemAtLocation_ReturnValue) == 0x000120, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_SpawnSystemAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000128, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, Temp_bool_IsClosed_Variable_4) == 0x000130, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::Temp_bool_IsClosed_Variable_4' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, K2Node_ComponentBoundEvent_Defencer) == 0x000138, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::K2Node_ComponentBoundEvent_Defencer' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, K2Node_ComponentBoundEvent_damageInfo) == 0x000140, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::K2Node_ComponentBoundEvent_damageInfo' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, K2Node_ComponentBoundEvent_hitCount) == 0x000210, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::K2Node_ComponentBoundEvent_hitCount' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, K2Node_ComponentBoundEvent_AttackerComponent) == 0x000218, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::K2Node_ComponentBoundEvent_AttackerComponent' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_GetFloatValue_InTime_ImplicitCast) == 0x000220, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_GetFloatValue_InTime_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_Multiply_DoubleDouble_A_ImplicitCast) == 0x000228, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_Multiply_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_SetVariableFloat_InValue_ImplicitCast) == 0x000230, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_SetVariableFloat_InValue_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_GetFloatValue_InTime_ImplicitCast_1) == 0x000234, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_GetFloatValue_InTime_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_Multiply_DoubleDouble_A_ImplicitCast_1) == 0x000238, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_Multiply_DoubleDouble_A_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_SetVariableFloat_InValue_ImplicitCast_1) == 0x000240, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_SetVariableFloat_InValue_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_GetFloatValue_InTime_ImplicitCast_2) == 0x000244, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_GetFloatValue_InTime_ImplicitCast_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_Multiply_DoubleDouble_A_ImplicitCast_2) == 0x000248, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_Multiply_DoubleDouble_A_ImplicitCast_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_SetVariableFloat_InValue_ImplicitCast_2) == 0x000250, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_SetVariableFloat_InValue_ImplicitCast_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_GetFloatValue_InTime_ImplicitCast_3) == 0x000254, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_GetFloatValue_InTime_ImplicitCast_3' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_Multiply_DoubleDouble_A_ImplicitCast_3) == 0x000258, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_Multiply_DoubleDouble_A_ImplicitCast_3' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet, CallFunc_SetVariableFloat_InValue_ImplicitCast_3) == 0x000260, "Member 'BP_SkillEffect_SandTornadoBullet_C_ExecuteUbergraph_BP_SkillEffect_SandTornadoBullet::CallFunc_SetVariableFloat_InValue_ImplicitCast_3' has a wrong offset!");

// Function BP_SkillEffect_SandTornadoBullet.BP_SkillEffect_SandTornadoBullet_C.FadeOutEffect
// 0x0008 (0x0008 - 0x0000)
struct BP_SkillEffect_SandTornadoBullet_C_FadeOutEffect final
{
public:
	double                                        DeltaSecond;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SkillEffect_SandTornadoBullet_C_FadeOutEffect) == 0x000008, "Wrong alignment on BP_SkillEffect_SandTornadoBullet_C_FadeOutEffect");
static_assert(sizeof(BP_SkillEffect_SandTornadoBullet_C_FadeOutEffect) == 0x000008, "Wrong size on BP_SkillEffect_SandTornadoBullet_C_FadeOutEffect");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_FadeOutEffect, DeltaSecond) == 0x000000, "Member 'BP_SkillEffect_SandTornadoBullet_C_FadeOutEffect::DeltaSecond' has a wrong offset!");

// Function BP_SkillEffect_SandTornadoBullet.BP_SkillEffect_SandTornadoBullet_C.SetRandomValueIntoNiagaraVariable
// 0x0018 (0x0018 - 0x0000)
struct BP_SkillEffect_SandTornadoBullet_C_SetRandomValueIntoNiagaraVariable final
{
public:
	class UNiagaraComponent*                      NiagaraComp;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_RandomFloatInRange_ReturnValue;           // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetVariableFloat_InValue_ImplicitCast;    // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SkillEffect_SandTornadoBullet_C_SetRandomValueIntoNiagaraVariable) == 0x000008, "Wrong alignment on BP_SkillEffect_SandTornadoBullet_C_SetRandomValueIntoNiagaraVariable");
static_assert(sizeof(BP_SkillEffect_SandTornadoBullet_C_SetRandomValueIntoNiagaraVariable) == 0x000018, "Wrong size on BP_SkillEffect_SandTornadoBullet_C_SetRandomValueIntoNiagaraVariable");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_SetRandomValueIntoNiagaraVariable, NiagaraComp) == 0x000000, "Member 'BP_SkillEffect_SandTornadoBullet_C_SetRandomValueIntoNiagaraVariable::NiagaraComp' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_SetRandomValueIntoNiagaraVariable, CallFunc_RandomFloatInRange_ReturnValue) == 0x000008, "Member 'BP_SkillEffect_SandTornadoBullet_C_SetRandomValueIntoNiagaraVariable::CallFunc_RandomFloatInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_SandTornadoBullet_C_SetRandomValueIntoNiagaraVariable, CallFunc_SetVariableFloat_InValue_ImplicitCast) == 0x000010, "Member 'BP_SkillEffect_SandTornadoBullet_C_SetRandomValueIntoNiagaraVariable::CallFunc_SetVariableFloat_InValue_ImplicitCast' has a wrong offset!");

}

