#pragma once

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace PalServer::Params
{

// Function BP_SkillEffect_BubbleShot_Bullet.BP_SkillEffect_BubbleShot_Bullet_C.BndEvt__BP_SkillEffect_BubbleShot_Bullet_AttackFilter_K2Node_ComponentBoundEvent_1_OnAttackDelegate__DelegateSignature
// 0x00E8 (0x00E8 - 0x0000)
struct BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_AttackFilter_K2Node_ComponentBoundEvent_1_OnAttackDelegate__DelegateSignature final
{
public:
	class AActor*                                 Defencer;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FPalDamageInfo                         DamageInfo;                                        // 0x0008(0x00D0)(BlueprintVisible, BlueprintReadOnly, Parm)
	int32                                         HitCount;                                          // 0x00D8(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DC[0x4];                                       // 0x00DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    AttackerComponent;                                 // 0x00E0(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_AttackFilter_K2Node_ComponentBoundEvent_1_OnAttackDelegate__DelegateSignature) == 0x000008, "Wrong alignment on BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_AttackFilter_K2Node_ComponentBoundEvent_1_OnAttackDelegate__DelegateSignature");
static_assert(sizeof(BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_AttackFilter_K2Node_ComponentBoundEvent_1_OnAttackDelegate__DelegateSignature) == 0x0000E8, "Wrong size on BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_AttackFilter_K2Node_ComponentBoundEvent_1_OnAttackDelegate__DelegateSignature");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_AttackFilter_K2Node_ComponentBoundEvent_1_OnAttackDelegate__DelegateSignature, Defencer) == 0x000000, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_AttackFilter_K2Node_ComponentBoundEvent_1_OnAttackDelegate__DelegateSignature::Defencer' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_AttackFilter_K2Node_ComponentBoundEvent_1_OnAttackDelegate__DelegateSignature, DamageInfo) == 0x000008, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_AttackFilter_K2Node_ComponentBoundEvent_1_OnAttackDelegate__DelegateSignature::DamageInfo' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_AttackFilter_K2Node_ComponentBoundEvent_1_OnAttackDelegate__DelegateSignature, HitCount) == 0x0000D8, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_AttackFilter_K2Node_ComponentBoundEvent_1_OnAttackDelegate__DelegateSignature::HitCount' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_AttackFilter_K2Node_ComponentBoundEvent_1_OnAttackDelegate__DelegateSignature, AttackerComponent) == 0x0000E0, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_AttackFilter_K2Node_ComponentBoundEvent_1_OnAttackDelegate__DelegateSignature::AttackerComponent' has a wrong offset!");

// Function BP_SkillEffect_BubbleShot_Bullet.BP_SkillEffect_BubbleShot_Bullet_C.BndEvt__BP_SkillEffect_BubbleShot_Bullet_BubbleShotEffect_K2Node_ComponentBoundEvent_2_OnNiagaraSystemFinished__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_BubbleShotEffect_K2Node_ComponentBoundEvent_2_OnNiagaraSystemFinished__DelegateSignature final
{
public:
	class UNiagaraComponent*                      PSystem;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_BubbleShotEffect_K2Node_ComponentBoundEvent_2_OnNiagaraSystemFinished__DelegateSignature) == 0x000008, "Wrong alignment on BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_BubbleShotEffect_K2Node_ComponentBoundEvent_2_OnNiagaraSystemFinished__DelegateSignature");
static_assert(sizeof(BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_BubbleShotEffect_K2Node_ComponentBoundEvent_2_OnNiagaraSystemFinished__DelegateSignature) == 0x000008, "Wrong size on BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_BubbleShotEffect_K2Node_ComponentBoundEvent_2_OnNiagaraSystemFinished__DelegateSignature");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_BubbleShotEffect_K2Node_ComponentBoundEvent_2_OnNiagaraSystemFinished__DelegateSignature, PSystem) == 0x000000, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_BubbleShotEffect_K2Node_ComponentBoundEvent_2_OnNiagaraSystemFinished__DelegateSignature::PSystem' has a wrong offset!");

// Function BP_SkillEffect_BubbleShot_Bullet.BP_SkillEffect_BubbleShot_Bullet_C.BndEvt__BP_SkillEffect_BubbleShot_Bullet_DisableHomingTrigger_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// 0x0108 (0x0108 - 0x0000)
struct BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_DisableHomingTrigger_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFromSweep;                                        // 0x001C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             SweepResult;                                       // 0x0020(0x00E8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_DisableHomingTrigger_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_DisableHomingTrigger_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(sizeof(BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_DisableHomingTrigger_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature) == 0x000108, "Wrong size on BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_DisableHomingTrigger_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_DisableHomingTrigger_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_DisableHomingTrigger_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_DisableHomingTrigger_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_DisableHomingTrigger_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_DisableHomingTrigger_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_DisableHomingTrigger_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_DisableHomingTrigger_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_DisableHomingTrigger_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_DisableHomingTrigger_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, bFromSweep) == 0x00001C, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_DisableHomingTrigger_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::bFromSweep' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_DisableHomingTrigger_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, SweepResult) == 0x000020, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_DisableHomingTrigger_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::SweepResult' has a wrong offset!");

// Function BP_SkillEffect_BubbleShot_Bullet.BP_SkillEffect_BubbleShot_Bullet_C.BndEvt__BP_SkillEffect_BubbleShot_Bullet_MovementSphereRoot_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature
// 0x0118 (0x0118 - 0x0000)
struct BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_MovementSphereRoot_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    HitComponent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector                                NormalImpulse;                                     // 0x0018(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             Hit;                                               // 0x0030(0x00E8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_MovementSphereRoot_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature) == 0x000008, "Wrong alignment on BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_MovementSphereRoot_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature");
static_assert(sizeof(BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_MovementSphereRoot_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature) == 0x000118, "Wrong size on BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_MovementSphereRoot_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_MovementSphereRoot_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature, HitComponent) == 0x000000, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_MovementSphereRoot_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature::HitComponent' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_MovementSphereRoot_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_MovementSphereRoot_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_MovementSphereRoot_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_MovementSphereRoot_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_MovementSphereRoot_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature, NormalImpulse) == 0x000018, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_MovementSphereRoot_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature::NormalImpulse' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_MovementSphereRoot_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature, Hit) == 0x000030, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_BndEvt__BP_SkillEffect_BubbleShot_Bullet_MovementSphereRoot_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature::Hit' has a wrong offset!");

// Function BP_SkillEffect_BubbleShot_Bullet.BP_SkillEffect_BubbleShot_Bullet_C.ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet
// 0x0500 (0x0500 - 0x0000)
struct BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue;        // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue;          // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FClamp_ReturnValue;                       // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetFloatValue_ReturnValue;                // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable; // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_SelectFloat_ReturnValue;                  // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable_1;                     // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable_2;                     // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable_1;               // 0x003A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable_2;               // 0x003B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue_1;      // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SelectFloat_ReturnValue_1;                // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue_1;        // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FClamp_ReturnValue_1;                     // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetFloatValue_ReturnValue_1;              // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_64[0x4];                                       // 0x0064(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_1;      // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable_1; // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue_2;      // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue_2;        // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FClamp_ReturnValue_2;                     // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetFloatValue_ReturnValue_2;              // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_94[0x4];                                       // 0x0094(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_SelectFloat_ReturnValue_2;                // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_2;      // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable_2; // 0x00AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_AD[0x3];                                       // 0x00AD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x00B0(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue;            // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C1[0x7];                                       // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_3;      // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_4;      // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent;    // 0x00D8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor_1;           // 0x00E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp_1;            // 0x00E8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex;         // 0x00F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bFromSweep;             // 0x00F4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F5[0x3];                                       // 0x00F5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_ComponentBoundEvent_SweepResult;            // 0x00F8(0x00E8)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class AActor*                                 CallFunc_GetActionTargetActor_ReturnValue;         // 0x01E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x01E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x01E9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1EA[0x2];                                      // 0x01EA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_RandomFloatFromStream_ReturnValue;        // 0x01EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_5;      // 0x01F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_Event_DeltaSecond;                          // 0x01F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0200(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x0208(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_Defencer;               // 0x0220(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FPalDamageInfo                         K2Node_ComponentBoundEvent_damageInfo;             // 0x0228(0x00D0)()
	int32                                         K2Node_ComponentBoundEvent_hitCount;               // 0x02F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2FC[0x4];                                      // 0x02FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_AttackerComponent;      // 0x0300(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0308(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      CallFunc_SpawnSystemAtLocation_ReturnValue;        // 0x0320(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable_3;               // 0x0328(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_329[0x7];                                      // 0x0329(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_HitComponent;           // 0x0330(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor;             // 0x0338(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp;              // 0x0340(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_ComponentBoundEvent_NormalImpulse;          // 0x0348(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_ComponentBoundEvent_Hit;                    // 0x0360(0x00E8)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue;               // 0x0448(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue_1;             // 0x0450(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable_3;                     // 0x0458(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ClassClass_ReturnValue;          // 0x0459(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_45A[0x6];                                      // 0x045A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0460(0x0008)(NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0468(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_46C[0x4];                                      // 0x046C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Add_DoubleDouble_ReturnValue_1;           // 0x0470(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0478(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_479[0x7];                                      // 0x0479(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraComponent*                      K2Node_ComponentBoundEvent_PSystem;                // 0x0480(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetFloatValue_InTime_ImplicitCast;        // 0x0488(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_48C[0x4];                                      // 0x048C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast;     // 0x0490(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetVariableFloat_InValue_ImplicitCast;    // 0x0498(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetFloatValue_InTime_ImplicitCast_1;      // 0x049C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast_1;   // 0x04A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetVariableFloat_InValue_ImplicitCast_1;  // 0x04A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetFloatValue_InTime_ImplicitCast_2;      // 0x04AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast_2;   // 0x04B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetVariableFloat_InValue_ImplicitCast_2;  // 0x04B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BC[0x4];                                      // 0x04BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast_3;   // 0x04C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast_4;   // 0x04C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_VariableSet_ProjectileGravityScale_ImplicitCast; // 0x04D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4D4[0x4];                                      // 0x04D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Less_DoubleDouble_A_ImplicitCast;         // 0x04D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_B_ImplicitCast;     // 0x04E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_VariableSet_MaxSpeed_ImplicitCast;          // 0x04E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EC[0x4];                                      // 0x04EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Add_DoubleDouble_A_ImplicitCast;          // 0x04F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_VariableSet_HomingAccelerationMagnitude_ImplicitCast; // 0x04F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet) == 0x000008, "Wrong alignment on BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet");
static_assert(sizeof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet) == 0x000500, "Wrong size on BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, EntryPoint) == 0x000000, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, Temp_bool_Has_Been_Initd_Variable) == 0x000004, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, Temp_bool_IsClosed_Variable) == 0x000005, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_Subtract_DoubleDouble_ReturnValue) == 0x000008, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_Subtract_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_Divide_DoubleDouble_ReturnValue) == 0x000010, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_Divide_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_FClamp_ReturnValue) == 0x000018, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_FClamp_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_GetFloatValue_ReturnValue) == 0x000020, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_GetFloatValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable) == 0x000024, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_SelectFloat_ReturnValue) == 0x000028, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_SelectFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000030, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, Temp_bool_IsClosed_Variable_1) == 0x000038, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::Temp_bool_IsClosed_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, Temp_bool_IsClosed_Variable_2) == 0x000039, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::Temp_bool_IsClosed_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, Temp_bool_Has_Been_Initd_Variable_1) == 0x00003A, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::Temp_bool_Has_Been_Initd_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, Temp_bool_Has_Been_Initd_Variable_2) == 0x00003B, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::Temp_bool_Has_Been_Initd_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_Subtract_DoubleDouble_ReturnValue_1) == 0x000040, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_Subtract_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_SelectFloat_ReturnValue_1) == 0x000048, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_SelectFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_Divide_DoubleDouble_ReturnValue_1) == 0x000050, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_Divide_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_FClamp_ReturnValue_1) == 0x000058, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_FClamp_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_GetFloatValue_ReturnValue_1) == 0x000060, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_GetFloatValue_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_Multiply_DoubleDouble_ReturnValue_1) == 0x000068, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_Multiply_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable_1) == 0x000070, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_Subtract_DoubleDouble_ReturnValue_2) == 0x000078, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_Subtract_DoubleDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_Divide_DoubleDouble_ReturnValue_2) == 0x000080, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_Divide_DoubleDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_FClamp_ReturnValue_2) == 0x000088, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_FClamp_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_GetFloatValue_ReturnValue_2) == 0x000090, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_GetFloatValue_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_SelectFloat_ReturnValue_2) == 0x000098, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_SelectFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_Multiply_DoubleDouble_ReturnValue_2) == 0x0000A0, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_Multiply_DoubleDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, K2Node_Event_DeltaSeconds) == 0x0000A8, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable_2) == 0x0000AC, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, K2Node_CreateDelegate_OutputDelegate) == 0x0000B0, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_Less_DoubleDouble_ReturnValue) == 0x0000C0, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_Less_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_Multiply_DoubleDouble_ReturnValue_3) == 0x0000C8, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_Multiply_DoubleDouble_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_Multiply_DoubleDouble_ReturnValue_4) == 0x0000D0, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_Multiply_DoubleDouble_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, K2Node_ComponentBoundEvent_OverlappedComponent) == 0x0000D8, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::K2Node_ComponentBoundEvent_OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, K2Node_ComponentBoundEvent_OtherActor_1) == 0x0000E0, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::K2Node_ComponentBoundEvent_OtherActor_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, K2Node_ComponentBoundEvent_OtherComp_1) == 0x0000E8, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::K2Node_ComponentBoundEvent_OtherComp_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, K2Node_ComponentBoundEvent_OtherBodyIndex) == 0x0000F0, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::K2Node_ComponentBoundEvent_OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, K2Node_ComponentBoundEvent_bFromSweep) == 0x0000F4, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::K2Node_ComponentBoundEvent_bFromSweep' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, K2Node_ComponentBoundEvent_SweepResult) == 0x0000F8, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::K2Node_ComponentBoundEvent_SweepResult' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_GetActionTargetActor_ReturnValue) == 0x0001E0, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_GetActionTargetActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x0001E8, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_IsValid_ReturnValue) == 0x0001E9, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_RandomFloatFromStream_ReturnValue) == 0x0001EC, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_RandomFloatFromStream_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_Multiply_DoubleDouble_ReturnValue_5) == 0x0001F0, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_Multiply_DoubleDouble_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, K2Node_Event_DeltaSecond) == 0x0001F8, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::K2Node_Event_DeltaSecond' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_Add_DoubleDouble_ReturnValue) == 0x000200, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_MakeVector_ReturnValue) == 0x000208, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, K2Node_ComponentBoundEvent_Defencer) == 0x000220, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::K2Node_ComponentBoundEvent_Defencer' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, K2Node_ComponentBoundEvent_damageInfo) == 0x000228, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::K2Node_ComponentBoundEvent_damageInfo' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, K2Node_ComponentBoundEvent_hitCount) == 0x0002F8, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::K2Node_ComponentBoundEvent_hitCount' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, K2Node_ComponentBoundEvent_AttackerComponent) == 0x000300, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::K2Node_ComponentBoundEvent_AttackerComponent' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000308, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_SpawnSystemAtLocation_ReturnValue) == 0x000320, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_SpawnSystemAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, Temp_bool_Has_Been_Initd_Variable_3) == 0x000328, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::Temp_bool_Has_Been_Initd_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, K2Node_ComponentBoundEvent_HitComponent) == 0x000330, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::K2Node_ComponentBoundEvent_HitComponent' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, K2Node_ComponentBoundEvent_OtherActor) == 0x000338, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::K2Node_ComponentBoundEvent_OtherActor' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, K2Node_ComponentBoundEvent_OtherComp) == 0x000340, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::K2Node_ComponentBoundEvent_OtherComp' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, K2Node_ComponentBoundEvent_NormalImpulse) == 0x000348, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::K2Node_ComponentBoundEvent_NormalImpulse' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, K2Node_ComponentBoundEvent_Hit) == 0x000360, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::K2Node_ComponentBoundEvent_Hit' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_GetObjectClass_ReturnValue) == 0x000448, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_GetObjectClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_GetObjectClass_ReturnValue_1) == 0x000450, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_GetObjectClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, Temp_bool_IsClosed_Variable_3) == 0x000458, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::Temp_bool_IsClosed_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_NotEqual_ClassClass_ReturnValue) == 0x000459, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_NotEqual_ClassClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000460, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_Array_Add_ReturnValue) == 0x000468, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_Add_DoubleDouble_ReturnValue_1) == 0x000470, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_Add_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_IsValid_ReturnValue_1) == 0x000478, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, K2Node_ComponentBoundEvent_PSystem) == 0x000480, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::K2Node_ComponentBoundEvent_PSystem' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_GetFloatValue_InTime_ImplicitCast) == 0x000488, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_GetFloatValue_InTime_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_Multiply_DoubleDouble_A_ImplicitCast) == 0x000490, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_Multiply_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_SetVariableFloat_InValue_ImplicitCast) == 0x000498, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_SetVariableFloat_InValue_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_GetFloatValue_InTime_ImplicitCast_1) == 0x00049C, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_GetFloatValue_InTime_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_Multiply_DoubleDouble_A_ImplicitCast_1) == 0x0004A0, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_Multiply_DoubleDouble_A_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_SetVariableFloat_InValue_ImplicitCast_1) == 0x0004A8, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_SetVariableFloat_InValue_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_GetFloatValue_InTime_ImplicitCast_2) == 0x0004AC, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_GetFloatValue_InTime_ImplicitCast_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_Multiply_DoubleDouble_A_ImplicitCast_2) == 0x0004B0, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_Multiply_DoubleDouble_A_ImplicitCast_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_SetVariableFloat_InValue_ImplicitCast_2) == 0x0004B8, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_SetVariableFloat_InValue_ImplicitCast_2' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_Multiply_DoubleDouble_A_ImplicitCast_3) == 0x0004C0, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_Multiply_DoubleDouble_A_ImplicitCast_3' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_Multiply_DoubleDouble_A_ImplicitCast_4) == 0x0004C8, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_Multiply_DoubleDouble_A_ImplicitCast_4' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, K2Node_VariableSet_ProjectileGravityScale_ImplicitCast) == 0x0004D0, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::K2Node_VariableSet_ProjectileGravityScale_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_Less_DoubleDouble_A_ImplicitCast) == 0x0004D8, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_Less_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_Multiply_DoubleDouble_B_ImplicitCast) == 0x0004E0, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_Multiply_DoubleDouble_B_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, K2Node_VariableSet_MaxSpeed_ImplicitCast) == 0x0004E8, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::K2Node_VariableSet_MaxSpeed_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, CallFunc_Add_DoubleDouble_A_ImplicitCast) == 0x0004F0, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::CallFunc_Add_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet, K2Node_VariableSet_HomingAccelerationMagnitude_ImplicitCast) == 0x0004F8, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ExecuteUbergraph_BP_SkillEffect_BubbleShot_Bullet::K2Node_VariableSet_HomingAccelerationMagnitude_ImplicitCast' has a wrong offset!");

// Function BP_SkillEffect_BubbleShot_Bullet.BP_SkillEffect_BubbleShot_Bullet_C.FadeOutEffect
// 0x0008 (0x0008 - 0x0000)
struct BP_SkillEffect_BubbleShot_Bullet_C_FadeOutEffect final
{
public:
	double                                        DeltaSecond;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SkillEffect_BubbleShot_Bullet_C_FadeOutEffect) == 0x000008, "Wrong alignment on BP_SkillEffect_BubbleShot_Bullet_C_FadeOutEffect");
static_assert(sizeof(BP_SkillEffect_BubbleShot_Bullet_C_FadeOutEffect) == 0x000008, "Wrong size on BP_SkillEffect_BubbleShot_Bullet_C_FadeOutEffect");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_FadeOutEffect, DeltaSecond) == 0x000000, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_FadeOutEffect::DeltaSecond' has a wrong offset!");

// Function BP_SkillEffect_BubbleShot_Bullet.BP_SkillEffect_BubbleShot_Bullet_C.GetHomingEndDot
// 0x0018 (0x0018 - 0x0000)
struct BP_SkillEffect_BubbleShot_Bullet_C_GetHomingEndDot final
{
public:
	double                                        Dot;                                               // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue;            // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Less_DoubleDouble_A_ImplicitCast;         // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SkillEffect_BubbleShot_Bullet_C_GetHomingEndDot) == 0x000008, "Wrong alignment on BP_SkillEffect_BubbleShot_Bullet_C_GetHomingEndDot");
static_assert(sizeof(BP_SkillEffect_BubbleShot_Bullet_C_GetHomingEndDot) == 0x000018, "Wrong size on BP_SkillEffect_BubbleShot_Bullet_C_GetHomingEndDot");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_GetHomingEndDot, Dot) == 0x000000, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_GetHomingEndDot::Dot' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_GetHomingEndDot, CallFunc_Less_DoubleDouble_ReturnValue) == 0x000008, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_GetHomingEndDot::CallFunc_Less_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_GetHomingEndDot, CallFunc_Less_DoubleDouble_A_ImplicitCast) == 0x000010, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_GetHomingEndDot::CallFunc_Less_DoubleDouble_A_ImplicitCast' has a wrong offset!");

// Function BP_SkillEffect_BubbleShot_Bullet.BP_SkillEffect_BubbleShot_Bullet_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_SkillEffect_BubbleShot_Bullet_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SkillEffect_BubbleShot_Bullet_C_ReceiveTick) == 0x000004, "Wrong alignment on BP_SkillEffect_BubbleShot_Bullet_C_ReceiveTick");
static_assert(sizeof(BP_SkillEffect_BubbleShot_Bullet_C_ReceiveTick) == 0x000004, "Wrong size on BP_SkillEffect_BubbleShot_Bullet_C_ReceiveTick");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function BP_SkillEffect_BubbleShot_Bullet.BP_SkillEffect_BubbleShot_Bullet_C.SetRandomValueIntoNiagaraVariable
// 0x0008 (0x0008 - 0x0000)
struct BP_SkillEffect_BubbleShot_Bullet_C_SetRandomValueIntoNiagaraVariable final
{
public:
	class UNiagaraComponent*                      NiagaraComp;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SkillEffect_BubbleShot_Bullet_C_SetRandomValueIntoNiagaraVariable) == 0x000008, "Wrong alignment on BP_SkillEffect_BubbleShot_Bullet_C_SetRandomValueIntoNiagaraVariable");
static_assert(sizeof(BP_SkillEffect_BubbleShot_Bullet_C_SetRandomValueIntoNiagaraVariable) == 0x000008, "Wrong size on BP_SkillEffect_BubbleShot_Bullet_C_SetRandomValueIntoNiagaraVariable");
static_assert(offsetof(BP_SkillEffect_BubbleShot_Bullet_C_SetRandomValueIntoNiagaraVariable, NiagaraComp) == 0x000000, "Member 'BP_SkillEffect_BubbleShot_Bullet_C_SetRandomValueIntoNiagaraVariable::NiagaraComp' has a wrong offset!");

}

