#pragma once

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "Pal_structs.hpp"


namespace PalSDK::Params
{

// Function BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack.BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C.CalcCurrentLocation
// 0x00B0 (0x00B0 - 0x0000)
struct BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation final
{
public:
	double                                        DeltaTime;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Location;                                          // 0x0008(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Output;                                            // 0x0020(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue;        // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_1;      // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FMax_ReturnValue;                         // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_2;      // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x0060(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue;           // 0x0078(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0080(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0098(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation) == 0x000008, "Wrong alignment on BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation");
static_assert(sizeof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation) == 0x0000B0, "Wrong size on BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation, DeltaTime) == 0x000000, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation::DeltaTime' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation, Location) == 0x000008, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation::Location' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation, Output) == 0x000020, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation::Output' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000038, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation, CallFunc_Subtract_DoubleDouble_ReturnValue) == 0x000040, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation::CallFunc_Subtract_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation, CallFunc_Multiply_DoubleDouble_ReturnValue_1) == 0x000048, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation::CallFunc_Multiply_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation, CallFunc_FMax_ReturnValue) == 0x000050, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation::CallFunc_FMax_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation, CallFunc_Multiply_DoubleDouble_ReturnValue_2) == 0x000058, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation::CallFunc_Multiply_DoubleDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation, CallFunc_MakeVector_ReturnValue) == 0x000060, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation, CallFunc_GetActionCharacter_ReturnValue) == 0x000078, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation::CallFunc_GetActionCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000080, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation, CallFunc_Add_VectorVector_ReturnValue) == 0x000098, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_CalcCurrentLocation::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");

// Function BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack.BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C.ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack
// 0x05C0 (0x05C0 - 0x0000)
struct BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0018(0x0008)(NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaTime;                            // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue;           // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_CalcCurrentLocation_Location;             // 0x0030(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPalSkeletalMeshComponent*              CallFunc_GetMainMesh_ReturnValue;                  // 0x0048(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_GetRotation_Rotation;                     // 0x0050(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue;              // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalAnimInstance*                       K2Node_DynamicCast_AsPal_Anim_Instance;            // 0x0070(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_79[0x3];                                       // 0x0079(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UAnimMontage* Montage, class FName NotifyName)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x007C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8C[0x4];                                       // 0x008C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue_1;         // 0x0090(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FReserveMontage                        K2Node_MakeStruct_ReserveMontage;                  // 0x0098(0x0010)(NoDestructor)
	class UAnimMontage*                           CallFunc_GetCurrentMontage_ReturnValue;            // 0x00A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<struct FReserveMontage>                K2Node_MakeArray_Array;                            // 0x00B0(0x0010)(ReferenceParm)
	class UPalSkeletalMeshComponent*              CallFunc_GetMainMesh_ReturnValue_1;                // 0x00C0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           K2Node_CustomEvent_Montage;                        // 0x00C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName;                     // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue_1;            // 0x00D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchName_CmpSuccess;                      // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E1[0x7];                                       // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalAnimInstance*                       K2Node_DynamicCast_AsPal_Anim_Instance_1;          // 0x00E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F1[0x3];                                       // 0x00F1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UAnimMontage* Montage, class FName NotifyName)> K2Node_CreateDelegate_OutputDelegate_2;            // 0x00F4(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0104(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_105[0x3];                                      // 0x0105(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue_2;         // 0x0108(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue_3;         // 0x0110(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalSkeletalMeshComponent*              CallFunc_GetMainMesh_ReturnValue_2;                // 0x0118(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPalSkeletalMeshComponent*              CallFunc_GetMainMesh_ReturnValue_3;                // 0x0120(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_128[0x8];                                      // 0x0128(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_GetSocketTransform_ReturnValue;           // 0x0130(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_GetSocketTransform_ReturnValue_1;         // 0x0190(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakTransform_Location;                  // 0x01F0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation;                  // 0x0208(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale;                     // 0x0220(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakTransform_Location_1;                // 0x0238(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation_1;                // 0x0250(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale_1;                   // 0x0268(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0280(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue_1;              // 0x02E0(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetActorLocation_SweepHitResult;       // 0x0340(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_K2_SetActorLocation_ReturnValue;          // 0x0428(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_429[0x7];                                      // 0x0429(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0430(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_SkillEffect_Unique_ThunderSword_C*  CallFunc_FinishSpawningActor_ReturnValue;          // 0x0438(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0440(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_441[0x7];                                      // 0x0441(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_K2_SetActorTransform_SweepHitResult;      // 0x0448(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_K2_SetActorTransform_ReturnValue;         // 0x0530(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_531[0x7];                                      // 0x0531(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue_4;         // 0x0538(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue_5;         // 0x0540(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_K2_SetActorRotation_ReturnValue;          // 0x0548(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_549[0x7];                                      // 0x0549(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalCharacterMovementComponent*         CallFunc_GetPalCharacterMovementComponent_ReturnValue; // 0x0550(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue_6;         // 0x0558(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetGravityZMultiplier_ReturnValue;        // 0x0560(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_564[0x4];                                      // 0x0564(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalCharacterMovementComponent*         CallFunc_GetPalCharacterMovementComponent_ReturnValue_1; // 0x0568(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetAjustedTargetLocation_Location;        // 0x0570(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue_7;         // 0x0588(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalCharacterMovementComponent*         CallFunc_GetPalCharacterMovementComponent_ReturnValue_2; // 0x0590(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue_8;         // 0x0598(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalCharacterMovementComponent*         CallFunc_GetPalCharacterMovementComponent_ReturnValue_3; // 0x05A0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_GetRotation_DeltaTime_ImplicitCast;       // 0x05A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_CalcCurrentLocation_DeltaTime_ImplicitCast; // 0x05B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetGravityZMultiplier_rate_ImplicitCast;  // 0x05B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack) == 0x000010, "Wrong alignment on BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack");
static_assert(sizeof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack) == 0x0005C0, "Wrong size on BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, EntryPoint) == 0x000000, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000018, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, K2Node_Event_DeltaTime) == 0x000020, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::K2Node_Event_DeltaTime' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetActionCharacter_ReturnValue) == 0x000028, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetActionCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_CalcCurrentLocation_Location) == 0x000030, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_CalcCurrentLocation_Location' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetMainMesh_ReturnValue) == 0x000048, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetMainMesh_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetRotation_Rotation) == 0x000050, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetRotation_Rotation' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetAnimInstance_ReturnValue) == 0x000068, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetAnimInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, K2Node_DynamicCast_AsPal_Anim_Instance) == 0x000070, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::K2Node_DynamicCast_AsPal_Anim_Instance' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, K2Node_DynamicCast_bSuccess) == 0x000078, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, K2Node_CreateDelegate_OutputDelegate_1) == 0x00007C, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetActionCharacter_ReturnValue_1) == 0x000090, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetActionCharacter_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, K2Node_MakeStruct_ReserveMontage) == 0x000098, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::K2Node_MakeStruct_ReserveMontage' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetCurrentMontage_ReturnValue) == 0x0000A8, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetCurrentMontage_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, K2Node_MakeArray_Array) == 0x0000B0, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetMainMesh_ReturnValue_1) == 0x0000C0, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetMainMesh_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, K2Node_CustomEvent_Montage) == 0x0000C8, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::K2Node_CustomEvent_Montage' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, K2Node_CustomEvent_NotifyName) == 0x0000D0, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::K2Node_CustomEvent_NotifyName' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetAnimInstance_ReturnValue_1) == 0x0000D8, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetAnimInstance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, K2Node_SwitchName_CmpSuccess) == 0x0000E0, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::K2Node_SwitchName_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, K2Node_DynamicCast_AsPal_Anim_Instance_1) == 0x0000E8, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::K2Node_DynamicCast_AsPal_Anim_Instance_1' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, K2Node_DynamicCast_bSuccess_1) == 0x0000F0, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, K2Node_CreateDelegate_OutputDelegate_2) == 0x0000F4, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, K2Node_SwitchEnum_CmpSuccess) == 0x000104, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetActionCharacter_ReturnValue_2) == 0x000108, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetActionCharacter_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetActionCharacter_ReturnValue_3) == 0x000110, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetActionCharacter_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetMainMesh_ReturnValue_2) == 0x000118, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetMainMesh_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetMainMesh_ReturnValue_3) == 0x000120, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetMainMesh_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetSocketTransform_ReturnValue) == 0x000130, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetSocketTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetSocketTransform_ReturnValue_1) == 0x000190, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetSocketTransform_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_BreakTransform_Location) == 0x0001F0, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_BreakTransform_Location' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_BreakTransform_Rotation) == 0x000208, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_BreakTransform_Rotation' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_BreakTransform_Scale) == 0x000220, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_BreakTransform_Scale' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_BreakTransform_Location_1) == 0x000238, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_BreakTransform_Location_1' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_BreakTransform_Rotation_1) == 0x000250, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_BreakTransform_Rotation_1' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_BreakTransform_Scale_1) == 0x000268, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_BreakTransform_Scale_1' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_MakeTransform_ReturnValue) == 0x000280, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_MakeTransform_ReturnValue_1) == 0x0002E0, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_MakeTransform_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_K2_SetActorLocation_SweepHitResult) == 0x000340, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_K2_SetActorLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_K2_SetActorLocation_ReturnValue) == 0x000428, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_K2_SetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x000430, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_FinishSpawningActor_ReturnValue) == 0x000438, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_IsValid_ReturnValue) == 0x000440, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_K2_SetActorTransform_SweepHitResult) == 0x000448, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_K2_SetActorTransform_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_K2_SetActorTransform_ReturnValue) == 0x000530, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_K2_SetActorTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetActionCharacter_ReturnValue_4) == 0x000538, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetActionCharacter_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetActionCharacter_ReturnValue_5) == 0x000540, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetActionCharacter_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_K2_SetActorRotation_ReturnValue) == 0x000548, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_K2_SetActorRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetPalCharacterMovementComponent_ReturnValue) == 0x000550, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetPalCharacterMovementComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetActionCharacter_ReturnValue_6) == 0x000558, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetActionCharacter_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetGravityZMultiplier_ReturnValue) == 0x000560, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetGravityZMultiplier_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetPalCharacterMovementComponent_ReturnValue_1) == 0x000568, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetPalCharacterMovementComponent_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetAjustedTargetLocation_Location) == 0x000570, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetAjustedTargetLocation_Location' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetActionCharacter_ReturnValue_7) == 0x000588, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetActionCharacter_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetPalCharacterMovementComponent_ReturnValue_2) == 0x000590, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetPalCharacterMovementComponent_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetActionCharacter_ReturnValue_8) == 0x000598, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetActionCharacter_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetPalCharacterMovementComponent_ReturnValue_3) == 0x0005A0, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetPalCharacterMovementComponent_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_GetRotation_DeltaTime_ImplicitCast) == 0x0005A8, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_GetRotation_DeltaTime_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_CalcCurrentLocation_DeltaTime_ImplicitCast) == 0x0005B0, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_CalcCurrentLocation_DeltaTime_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack, CallFunc_SetGravityZMultiplier_rate_ImplicitCast) == 0x0005B8, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_ExecuteUbergraph_BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack::CallFunc_SetGravityZMultiplier_rate_ImplicitCast' has a wrong offset!");

// Function BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack.BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C.GetAjustedTargetLocation
// 0x00A0 (0x00A0 - 0x0000)
struct BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation final
{
public:
	struct FVector                                Location;                                          // 0x0000(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_GetActionTarget_ReturnValue;              // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetTargetLocation_ReturnValue;            // 0x0020(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCapsuleComponent*                      CallFunc_GetComponentByClass_ReturnValue;          // 0x0040(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0048(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x0068(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x0080(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_MakeVector_Z_ImplicitCast;                // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation) == 0x000008, "Wrong alignment on BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation");
static_assert(sizeof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation) == 0x0000A0, "Wrong size on BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation, Location) == 0x000000, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation::Location' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation, CallFunc_GetActionTarget_ReturnValue) == 0x000018, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation::CallFunc_GetActionTarget_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation, CallFunc_GetTargetLocation_ReturnValue) == 0x000020, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation::CallFunc_GetTargetLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation, CallFunc_IsValid_ReturnValue) == 0x000038, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation, CallFunc_GetComponentByClass_ReturnValue) == 0x000040, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000048, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation, CallFunc_IsValid_ReturnValue_1) == 0x000060, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation, CallFunc_MakeVector_ReturnValue) == 0x000068, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation, CallFunc_Subtract_VectorVector_ReturnValue) == 0x000080, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation, CallFunc_MakeVector_Z_ImplicitCast) == 0x000098, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_GetAjustedTargetLocation::CallFunc_MakeVector_Z_ImplicitCast' has a wrong offset!");

// Function BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack.BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C.TickAction
// 0x0004 (0x0004 - 0x0000)
struct BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_TickAction final
{
public:
	float                                         DeltaTime;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_TickAction) == 0x000004, "Wrong alignment on BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_TickAction");
static_assert(sizeof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_TickAction) == 0x000004, "Wrong size on BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_TickAction");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_TickAction, DeltaTime) == 0x000000, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_TickAction::DeltaTime' has a wrong offset!");

// Function BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack.BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C.UpdateAttackState
// 0x0010 (0x0010 - 0x0000)
struct BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_UpdateAttackState final
{
public:
	class UAnimMontage*                           Montage;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   NotifyName;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_UpdateAttackState) == 0x000008, "Wrong alignment on BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_UpdateAttackState");
static_assert(sizeof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_UpdateAttackState) == 0x000010, "Wrong size on BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_UpdateAttackState");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_UpdateAttackState, Montage) == 0x000000, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_UpdateAttackState::Montage' has a wrong offset!");
static_assert(offsetof(BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_UpdateAttackState, NotifyName) == 0x000008, "Member 'BP_ActionUnique_ThunderDragonMan_ThunderSwordAttack_C_UpdateAttackState::NotifyName' has a wrong offset!");

}

